### ISSUE TITLE
Daylight Savings Not Supported

### ISSUE THREAD

**Issue by gregorypratt** [DrewDahlman/Phonegap-LocalNotification#12]
This plugin doesn't seem to support daylight savings.

When I schedule a notification for say 13:00, it doesn't appear until 14:00 (because time is +1 hours ahead).

**Comment by DrewDahlman** [comment]
Answered on SO but I will also answer here. Because the plugin uses the phones time to set the date and time you should be just fine - make sure that you're setting the time properly also that your phone is running the correct time. I have tested this around daylight savings and never ran into an issue..
